giantswarm/apptestctl

Makefile, integration/test/bootstrap/setup.sh
Generated code from `devctl gen makefile -f cli`.
=> Add Makefile

README.md
Just added a simple command to README.
=> add a sample command to README

CHANGELOG.md, cmd/bootstrap/runner.go, go.mod, go.sum
=>  Enable persistence in chartmuseum via its app CR

.circleci/config.yml, CHANGELOG.md, Dockerfile
This PR adds a Dockerfile and the required CI configuration to build and push this to quay.io/giantswarm/apptestctl (I already created the repo at quay)
=> Add container build

CHANGELOG.md
=> Add changelog for printer columns on app and chart CRDs

CHANGELOG.md, Makefile, cmd/command.go, cmd/version/command.go, cmd/version/runner.go, main.go
- fix version printing in `version` command
=> Add version info

CHANGELOG.md, cmd/bootstrap/runner.go, cmd/bootstrap/template.go
Fixes https://github.com/giantswarm/apptestctl/issues/77
=> Wait for ready chartmuseum pod

CHANGELOG.md, cmd/bootstrap/runner.go, cmd/bootstrap/template.go
=> Update app operator to 4.0.2

CHANGELOG.md, cmd/bootstrap/flag.go, cmd/bootstrap/runner.go
Giving `--github-token` to `apptestctl bootstrap` to avoid the rate limitting.
=> GitHub token as flag

CHANGELOG.md, cmd/bootstrap/runner.go, cmd/bootstrap/template.go
=> Update to app-operator v5.1.1 and chart-operator v2.18.1

CHANGELOG.md, cmd/bootstrap/runner.go
=> Use latest operators

CHANGELOG.md, cmd/bootstrap/template.go
=> Use ClusterFirst for chart-operator DNS settings

CHANGELOG.md, pkg/crds/appcatalogentries.yaml, pkg/crds/appcatalogs.yaml, pkg/crds/apps.yaml, pkg/crds/catalogs.yaml, pkg/crds/charts.yaml
=> Run make sync-crds

CHANGELOG.md, cmd/bootstrap/runner.go
=> Fix install-operators flag

CHANGELOG.md, pkg/crds/appcatalogentries.yaml, pkg/crds/apps.yaml
=> Sync CRDs with apiextensions-application

CHANGELOG.md, pkg/crds/catalogs.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/22554
=> Update application.giantswarm.io/v1alpha1 Catalog

CHANGELOG.md, pkg/crds/apps.yaml
=> Refreash App CRD

CHANGELOG.md, pkg/crds/apps.yaml, pkg/crds/charts.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/23699
=> Updating crds

CHANGELOG.md, pkg/crds/appcatalogentries.yaml
=> AppCatalogEntries: Rename `nginx-ingress-controller-app` to `ingress-nginx`.

go.mod
An attempt to re-enable renovate to work in this repo.
=> Tidy up go.mod

.nancy-ignore, CHANGELOG.md, hack/sync-crds.sh, pkg/crds/crds.go, pkg/crds/policyexception.yaml
Signed-off-by: Matias Charriere <matias@giantswarm.io>
=> Add PolicyException CRD

.nancy-ignore
To unblock CI.
Upgrading the dependency seems too complicated for me.
=> Add CVE-2024-25620 to .nancy-ignore

go.mod
=> Remove ineffective replacement

CHANGELOG.md, hack/sync-crds.sh, pkg/crds/crds.go, pkg/crds/podmonitors.yaml, pkg/crds/prometheuses.yaml, pkg/crds/prometheusrules.yaml, pkg/crds/servicemonitors.yaml
Towards testing https://github.com/giantswarm/sloth-app/pull/116
=> add prometheus rules crds

CHANGELOG.md, pkg/crds/scaledobjects.yaml
Towards https://github.com/giantswarm/giantswarm/issues/33851
=> add ScaledObjects CRDs
